# TCCC Device Configuration
# Generated on: Fri Mar 21 12:24:03 AM PDT 2025

audio:
  input:
    device: 0  # Razer Seiren V3 Mini
    name: "Razer Seiren V3 Mini"
    fallback_device: 1
  output:
    device: "hdmi"
    name: "HDMI Audio Output"
    fallback_device: "default"
  
display:
  type: "displayport"  # Using DisplayPort connection instead of HDMI
  name: "Waveshare DisplayPort Monitor"
  resolution: "1560x720"
  rotation: "right"  # Display is rotated

hardware:
  platform: "jetson_nano"
  memory: "4GB"
  optimize_for_device: true
