# Data Store Configuration

# Database configuration
database:
  # Database type (sqlite, mysql, postgres)
  type: "sqlite"
  
  # SQLite specific configuration
  sqlite:
    # Path to database file
    database_path: "data/tccc.db"
    
    # Use WAL mode for concurrent access
    wal_mode: true
    
    # Journal mode (delete, truncate, persist, memory, wal, off)
    journal_mode: "wal"
    
    # Synchronous mode (0=OFF, 1=NORMAL, 2=FULL, 3=EXTRA)
    synchronous: 1
    
    # Cache size in KB
    cache_size: 2000
    
    # Page size in bytes
    page_size: 4096
    
    # Auto vacuum mode (0=NONE, 1=FULL, 2=INCREMENTAL)
    auto_vacuum: 1
    
    # Temp store mode (0=DEFAULT, 1=FILE, 2=MEMORY)
    temp_store: 2
    
    # Maximum number of connections in the pool
    max_connections: 10

# Storage configuration
storage:
  # Base directory for data storage
  base_dir: "data/storage"
  
  # Maximum storage size in MB (0 for unlimited)
  max_size_mb: 0
  
  # Autoclean old data when storage is full
  auto_clean: true
  
  # Default storage format (json, pickle, binary)
  default_format: "json"

# Backup configuration
backup:
  # Enable automatic backups
  enabled: true
  
  # Backup directory
  directory: "data/backups"
  
  # Backup interval in hours
  interval_hours: 24
  
  # Maximum number of backups to keep
  max_backups: 7
  
  # Compression level (0-9, 0=no compression)
  compression_level: 6

# Schema configuration
schema:
  # Enable schema validation
  validate: true
  
  # Auto-migrate schema changes
  auto_migrate: false
  
  # Schema definitions location
  definitions_path: "config/schemas/"

# Timeline configuration
timeline:
  # Default time window for queries in seconds
  default_time_window: 3600
  
  # Maximum time window for queries in seconds
  max_time_window: 86400
  
  # Time resolution in seconds
  resolution: 1
  
  # Time zones to store (UTC, local, both)
  time_zones: "both"

# Query configuration
query:
  # Enable query caching
  cache_enabled: true
  
  # Cache time-to-live in seconds
  cache_ttl: 300
  
  # Maximum number of results per query
  max_results: 1000
  
  # Default page size for paginated queries
  default_page_size: 50
  
  # Enable fuzzy matching for text search
  fuzzy_matching: true
  
  # Fuzzy matching threshold (0.0-1.0)
  fuzzy_threshold: 0.8

# Security configuration
security:
  # Enable data encryption at rest
  encrypt_data: false
  
  # Encryption key file (environment variable: TCCC_ENCRYPTION_KEY)
  encryption_key_file: "config/security/encryption.key"
  
  # Hash sensitive data in queries
  hash_sensitive_data: true
  
  # Salt for hashing (environment variable: TCCC_HASH_SALT)
  hash_salt: "${TCCC_HASH_SALT}"
  
  # Enable access logging
  access_logging: true
  
  # Log file for access logs
  access_log_file: "logs/data_store_access.log"

# Retention configuration
retention:
  # Enable data retention policies
  enabled: true
  
  # Default retention period in days
  default_period_days: 90
  
  # Retention periods by data type in days
  periods:
    events: 90
    reports: 365
    sessions: 30
    metrics: 180
  
  # Data purge interval in hours
  purge_interval_hours: 24
  
  # Archive data before purging
  archive_before_purge: true
  
  # Archive format (zip, tar, none)
  archive_format: "zip"

# Context generation for LLM
context:
  # Maximum context size in tokens
  max_tokens: 2000
  
  # Default time window for context in seconds
  time_window: 300
  
  # Include metadata in context
  include_metadata: true
  
  # Order contexts by (time, relevance)
  order_by: "time"
  
  # Fusion method for combining context pieces
  fusion_method: "concatenate"

# Performance optimization
performance:
  # Enable indexes for fast querying
  enable_indexes: true
  
  # Use prepared statements for repeated queries
  use_prepared_statements: true
  
  # Enable query optimization
  optimize_queries: true
  
  # Batch size for bulk operations
  batch_size: 100
  
  # Vacuum database interval in hours (0 to disable)
  vacuum_interval_hours: 168
  
  # Analyze database interval in hours (0 to disable)
  analyze_interval_hours: 24
  
  # Jetson Orin Nano specific optimizations
  jetson:
    # Optimize for NVMe storage
    nvme_optimized: true
    
    # Minimize disk IO during transcription
    minimize_io_during_transcription: true
    
    # Use memory mapped files
    use_memory_mapping: true
    
    # Memory limit for caching in MB
    memory_limit_mb: 512