advanced:
  debug_mode: false
  sdl_audiodriver: ''
  sdl_videodriver: ''
  show_touch_points: false
display:
  fullscreen: true
  height: 720
  orientation: landscape
  touch:
    calibration_enabled: true
    device: WaveShare Touchscreen
    enabled: true
    regions:
      card_button:
        enabled: true
        rect:
        - -100
        - 60
        - 100
        - 40
      toggle_view:
        enabled: true
        rect:
        - 0
        - -50
        - -1
        - 50
      transcription_scroll:
        enabled: true
        rect:
        - 0
        - 110
        - 585
        - 560
    sensitivity: 1.0
    transformation_matrix:
    - 0
    - 1
    - 0
    - -1
    - 0
    - 1
    - 0
    - 0
    - 1
  width: 1560
hardware:
  auto_detect: true
  jetson:
    framebuffer_device: /dev/fb0
    performance:
      fps_limit_ac: 30
      fps_limit_battery: 15
    power_save_mode: true
    use_framebuffer: true
    use_hardware_acceleration: true
  waveshare:
    backlight:
      default_value: 200
      enabled: false  # Disabled: Path /sys/class/backlight/waveshare/brightness does not exist
      max_value: 255
      path: /sys/class/backlight/waveshare/brightness
    hdmi_cvt: 720 1560 60 6 0 0 0
    hdmi_group: 2
    hdmi_mode: 87
    model: 6.25_inch
    rotation: 1
performance:
  log_performance: true
  monitor_enabled: true
  show_fps: false
  target_fps: 30
ui:
  alt_logo: images/green_logo.png
  animations:
    enabled: true
    fade_in: true
    scroll_smooth: true
    transition_speed_ms: 300
  color_schemes:
    dark:
      alert:
      - 255
      - 0
      - 0
      background:
      - 0
      - 0
      - 0
      header:
      - 0
      - 0
      - 255
      highlight:
      - 255
      - 215
      - 0
      success:
      - 0
      - 200
      - 0
      text:
      - 255
      - 255
      - 255
    light:
      alert:
      - 200
      - 0
      - 0
      background:
      - 240
      - 240
      - 240
      header:
      - 50
      - 50
      - 200
      highlight:
      - 200
      - 160
      - 0
      success:
      - 0
      - 150
      - 0
      text:
      - 10
      - 10
      - 10
  font_scale: 1.0
  large_font_size: 36
  layout:
    column_1_width: 0.38
    column_2_width: 0.34
  logo: images/blue_logo.png
  max_event_items: 8
  max_transcription_items: 10
  medium_font_size: 28
  small_font_size: 22
  theme: dark
