# Document Library Configuration

# Storage settings
storage:
  # Storage type (file, database, vector_db)
  type: "file"
  
  # Base directory for file storage
  base_dir: "data/documents"
  
  # File retention policy (in days, 0 for indefinite)
  retention_days: 0
  
  # Maximum storage size (in MB, 0 for unlimited)
  max_size_mb: 1024
  
  # Compression level (0-9, 0 for no compression)
  compression_level: 6
  
# Search settings
search:
  # Search provider (simple, elasticsearch, faiss)
  provider: "simple"
  
  # Enable semantic search
  semantic_search: true
  
  # Embedding model for semantic search
  embedding_model: "all-MiniLM-L6-v2"
  
  # Minimum similarity score for matches (0.0-1.0)
  min_similarity: 0.7
  
  # Default results limit
  default_results: 5
  
  # Maximum results limit
  max_results: 20
  
  # Enable fuzzy matching
  fuzzy_matching: true
  
# Indexing settings
indexing:
  # Automatic indexing of new documents
  auto_index: true
  
  # Index update frequency (in seconds)
  update_frequency: 300
  
  # Maximum document size to index (in KB)
  max_document_size_kb: 5120
  
  # Excluded file extensions
  excluded_extensions:
    - ".tmp"
    - ".bak"
    - ".log"
  
  # Document types to process
  document_types:
    - text: [".txt", ".md", ".html"]
    - pdf: [".pdf"]
    - office: [".docx", ".xlsx", ".pptx"]
    - medical: [".dicom", ".hl7"]

# Access control
access_control:
  # Enable access control
  enabled: false
  
  # Default access level (public, restricted, private)
  default_access: "public"
  
  # Role-based access
  roles:
    - name: "admin"
      permissions: ["read", "write", "delete", "share"]
    - name: "user"
      permissions: ["read", "write"]
    - name: "viewer"
      permissions: ["read"]

# Monitoring
monitoring:
  # Enable usage tracking
  track_usage: true
  
  # Log access events
  log_access: true
  
  # Log level for document operations
  log_level: "INFO"