# Speech-to-Text Engine Configuration

# Model settings
model:
  # Model type (whisper, faster-whisper)
  type: "faster-whisper"
  
  # Model size (tiny, small, medium, large-v2, large-v3)
  size: "tiny.en"
  
  # Model file path (if local model is used)
  path: "models/stt"
  
  # Batch size for inference
  batch_size: 1
  
  # Computation precision (float16, int8)
  compute_type: "float16"
  
  # Language
  language: "en"
  
  # Beam size for decoding
  beam_size: 5

# Diarization settings
diarization:
  # Enable speaker diarization
  enabled: true
  
  # Number of speakers (0 for auto-detection)
  num_speakers: 0
  
  # Minimum speakers to detect
  min_speakers: 1
  
  # Maximum speakers to detect
  max_speakers: 10
  
  # Clustering method (spectral, umap)
  clustering_method: "spectral"
  
  # Speaker embeddings model
  embeddings_model: "speechbrain/spkrec-ecapa-voxceleb"

# Transcription settings
transcription:
  # Minimum confidence threshold for word inclusion
  confidence_threshold: 0.6
  
  # Include word timestamps
  word_timestamps: true
  
  # Include punctuation
  include_punctuation: true
  
  # Include capitalization
  include_capitalization: true
  
  # Include numeric formatting
  format_numbers: true
  
  # Segment length in seconds
  segment_length: 30

# Custom vocabulary
vocabulary:
  # Enable custom vocabulary
  enabled: true
  
  # Path to vocabulary file
  path: "config/vocabulary/custom_terms.txt"
  
  # Vocabulary boost factor (higher value gives more weight)
  boost: 10.0

# Hardware acceleration settings
hardware:
  # Enable hardware acceleration (set to false for CPU only)
  enable_acceleration: false
  
  # CUDA device ID (-1 for CPU only)
  cuda_device: -1
  
  # Enable TensorRT optimization
  use_tensorrt: false
  
  # CUDA stream configuration
  cuda_streams: 1
  
  # Memory limit in MB
  memory_limit_mb: 2048
  
  # CPU threads for CPU-bound operations
  cpu_threads: 4
  
  # Quantization (INT8, FP16, FP32)
  quantization: "INT8"

# Streaming settings
streaming:
  # Enable streaming transcription
  enabled: true
  
  # Partial results interval in milliseconds
  partial_results_interval_ms: 500
  
  # Maximum context length in seconds
  max_context_length_sec: 60
  
  # Stability threshold for streaming results
  stability_threshold: 0.8